"""
This type stub file was generated by pyright.
"""

def connection_requires_http_tunnel(proxy_url=..., proxy_config=..., destination_scheme=...): # -> bool:
    """
    Returns True if the connection requires an HTTP CONNECT through the proxy.

    :param URL proxy_url:
        URL of the proxy.
    :param ProxyConfig proxy_config:
        Proxy configuration from poolmanager.py
    :param str destination_scheme:
        The scheme of the destination. (i.e https, http, etc)
    """
    ...

def create_proxy_ssl_context(ssl_version, cert_reqs, ca_certs=..., ca_cert_dir=..., ca_cert_data=...): # -> SSLContext:
    """
    Generates a default proxy ssl context if one hasn't been provided by the
    user.
    """
    ...

