"""
This type stub file was generated by pyright.
"""

SSL_BLOCKSIZE = ...
class SSLTransport:
    """
    The SSLTransport wraps an existing socket and establishes an SSL connection.

    Contrary to Python's implementation of SSLSocket, it allows you to chain
    multiple TLS connections together. It's particularly useful if you need to
    implement TLS within TLS.

    The class supports most of the socket API operations.
    """
    def __init__(self, socket, ssl_context, server_hostname=..., suppress_ragged_eofs=...) -> None:
        """
        Create an SSLTransport around socket using the provided ssl_context.
        """
        ...
    
    def __enter__(self): # -> Self:
        ...
    
    def __exit__(self, *_): # -> None:
        ...
    
    def fileno(self):
        ...
    
    def read(self, len=..., buffer=...): # -> Literal[0] | None:
        ...
    
    def recv(self, len=..., flags=...): # -> Literal[0] | None:
        ...
    
    def recv_into(self, buffer, nbytes=..., flags=...): # -> Literal[0] | None:
        ...
    
    def sendall(self, data, flags=...): # -> None:
        ...
    
    def send(self, data, flags=...): # -> None:
        ...
    
    def makefile(self, mode=..., buffering=..., encoding=..., errors=..., newline=...): # -> SocketIO | BufferedRWPair[SocketIO] | BufferedReader[SocketIO] | BufferedWriter | TextIOWrapper[_WrappedBuffer]:
        """
        Python's httpclient uses makefile and buffered io when reading HTTP
        messages and we need to support it.

        This is unfortunately a copy and paste of socket.py makefile with small
        changes to point to the socket directly.
        """
        ...
    
    def unwrap(self): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def getpeercert(self, binary_form=...):
        ...
    
    def version(self):
        ...
    
    def cipher(self):
        ...
    
    def selected_alpn_protocol(self):
        ...
    
    def selected_npn_protocol(self):
        ...
    
    def shared_ciphers(self):
        ...
    
    def compression(self):
        ...
    
    def settimeout(self, value): # -> None:
        ...
    
    def gettimeout(self):
        ...
    


