"""
This type stub file was generated by pyright.
"""

import logging
import warnings
import urllib3_secure_extra
from logging import NullHandler
from . import exceptions
from ._version import __version__
from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
from .filepost import encode_multipart_formdata
from .poolmanager import PoolManager, ProxyManager, proxy_from_url
from .response import HTTPResponse
from .util.request import make_headers
from .util.retry import Retry
from .util.timeout import Timeout
from .util.url import get_host

"""
Python HTTP library with thread-safe connection pooling, file post support, user friendly, and more
"""
__author__ = ...
__license__ = ...
__version__ = ...
__all__ = ("HTTPConnectionPool", "HTTPSConnectionPool", "PoolManager", "ProxyManager", "HTTPResponse", "Retry", "Timeout", "add_stderr_logger", "connection_from_url", "disable_warnings", "encode_multipart_formdata", "get_host", "make_headers", "proxy_from_url")
def add_stderr_logger(level=...): # -> StreamHandler[TextIO]:
    """
    Helper for quickly adding a StreamHandler to the logger. Useful for
    debugging.

    Returns the handler after adding it.
    """
    ...

def disable_warnings(category=...): # -> None:
    """
    Helper for quickly disabling all urllib3 warnings.
    """
    ...

