"""
This type stub file was generated by pyright.
"""

import io
import brotlicffi as brotli

log = ...
class DeflateDecoder:
    def __init__(self) -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def decompress(self, data): # -> bytes:
        ...
    


class GzipDecoderState:
    FIRST_MEMBER = ...
    OTHER_MEMBERS = ...
    SWALLOW_DATA = ...


class GzipDecoder:
    def __init__(self) -> None:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def decompress(self, data): # -> bytes:
        ...
    


if brotli is not None:
    class BrotliDecoder:
        def __init__(self) -> None:
            ...
        
        def flush(self): # -> Literal[b""]:
            ...
        
    
    
class MultiDecoder:
    """
    From RFC7231:
        If one or more encodings have been applied to a representation, the
        sender that applied the encodings MUST generate a Content-Encoding
        header field that lists the content codings in the order in which
        they were applied.
    """
    def __init__(self, modes) -> None:
        ...
    
    def flush(self): # -> Any | Literal[b""]:
        ...
    
    def decompress(self, data): # -> bytes:
        ...
    


class HTTPResponse(io.IOBase):
    """
    HTTP Response container.

    Backwards-compatible with :class:`http.client.HTTPResponse` but the response ``body`` is
    loaded and decoded on-demand when the ``data`` property is accessed.  This
    class is also compatible with the Python standard library's :mod:`io`
    module, and can hence be treated as a readable object in the context of that
    framework.

    Extra parameters for behaviour not present in :class:`http.client.HTTPResponse`:

    :param preload_content:
        If True, the response's body will be preloaded during construction.

    :param decode_content:
        If True, will attempt to decode the body based on the
        'content-encoding' header.

    :param original_response:
        When this HTTPResponse wrapper is generated from an :class:`http.client.HTTPResponse`
        object, it's convenient to include the original for debug purposes. It's
        otherwise unused.

    :param retries:
        The retries contains the last :class:`~urllib3.util.retry.Retry` that
        was used during the request.

    :param enforce_content_length:
        Enforce content length checking. Body returned by server must match
        value of Content-Length header, if present. Otherwise, raise error.
    """
    CONTENT_DECODERS = ...
    if brotli is not None:
        ...
    REDIRECT_STATUSES = ...
    def __init__(self, body=..., headers=..., status=..., version=..., reason=..., strict=..., preload_content=..., decode_content=..., original_response=..., pool=..., connection=..., msg=..., retries=..., enforce_content_length=..., request_method=..., request_url=..., auto_close=...) -> None:
        ...
    
    def get_redirect_location(self): # -> Literal[False]:
        """
        Should we redirect and where to?

        :returns: Truthy redirect location string if we got a redirect status
            code and valid location. ``None`` if redirect status and no
            location. ``False`` if not a redirect status code.
        """
        ...
    
    def release_conn(self): # -> None:
        ...
    
    def drain_conn(self): # -> None:
        """
        Read and discard any remaining HTTP response data in the response connection.

        Unread data in the HTTPResponse connection blocks the connection from being released back to the pool.
        """
        ...
    
    @property
    def data(self): # -> str | Any | bytes | None:
        ...
    
    @property
    def connection(self): # -> None:
        ...
    
    def isclosed(self): # -> bool:
        ...
    
    def tell(self): # -> int:
        """
        Obtain the number of bytes pulled over the wire so far. May differ from
        the amount of content returned by :meth:``urllib3.response.HTTPResponse.read``
        if bytes are encoded on the wire (e.g, compressed).
        """
        ...
    
    DECODER_ERROR_CLASSES = ...
    if brotli is not None:
        ...
    def read(self, amt=..., decode_content=..., cache_content=...): # -> Any | bytes | None:
        """
        Similar to :meth:`http.client.HTTPResponse.read`, but with two additional
        parameters: ``decode_content`` and ``cache_content``.

        :param amt:
            How much of the content to read. If specified, caching is skipped
            because it doesn't make sense to cache partial content as the full
            response.

        :param decode_content:
            If True, will attempt to decode the body based on the
            'content-encoding' header.

        :param cache_content:
            If True, will save the returned data such that the same result is
            returned despite of the state of the underlying file object. This
            is useful if you want the ``.data`` property to continue working
            after having ``.read()`` the file object. (Overridden if ``amt`` is
            set.)
        """
        ...
    
    def stream(self, amt=..., decode_content=...): # -> Generator[Any | bytes, Any, None]:
        """
        A generator wrapper for the read() method. A call will block until
        ``amt`` bytes have been read from the connection or until the
        connection is closed.

        :param amt:
            How much of the content to read. The generator will return up to
            much data per iteration, but may return less. This is particularly
            likely when using compressed data. However, the empty string will
            never be returned.

        :param decode_content:
            If True, will attempt to decode the body based on the
            'content-encoding' header.
        """
        ...
    
    @classmethod
    def from_httplib(ResponseCls, r, **response_kw): # -> Self:
        """
        Given an :class:`http.client.HTTPResponse` instance ``r``, return a
        corresponding :class:`urllib3.response.HTTPResponse` object.

        Remaining parameters are passed to the HTTPResponse constructor, along
        with ``original_response=r``.
        """
        ...
    
    def getheaders(self): # -> HTTPHeaderDict:
        ...
    
    def getheader(self, name, default=...):
        ...
    
    def info(self): # -> HTTPHeaderDict:
        ...
    
    def close(self): # -> None:
        ...
    
    @property
    def closed(self): # -> bool:
        ...
    
    def fileno(self):
        ...
    
    def flush(self): # -> None:
        ...
    
    def readable(self): # -> Literal[True]:
        ...
    
    def readinto(self, b): # -> int:
        ...
    
    def supports_chunked_reads(self): # -> bool:
        """
        Checks if the underlying file-like object looks like a
        :class:`http.client.HTTPResponse` object. We do this by testing for
        the fp attribute. If it is present we assume it returns raw chunks as
        processed by read_chunked().
        """
        ...
    
    def read_chunked(self, amt=..., decode_content=...): # -> Generator[Any | bytes, Any, None]:
        """
        Similar to :meth:`HTTPResponse.read`, but with an additional
        parameter: ``decode_content``.

        :param amt:
            How much of the content to read. If specified, caching is skipped
            because it doesn't make sense to cache partial content as the full
            response.

        :param decode_content:
            If True, will attempt to decode the body based on the
            'content-encoding' header.
        """
        ...
    
    def geturl(self): # -> None:
        """
        Returns the URL that was the source of this response.
        If the request that generated this response redirected, this method
        will return the final redirect location.
        """
        ...
    
    def __iter__(self): # -> Generator[bytes | Any, Any, None]:
        ...
    


