"""
This type stub file was generated by pyright.
"""

"""
This module provides means to detect the App Engine environment.
"""
def is_appengine(): # -> bool:
    ...

def is_appengine_sandbox(): # -> bool:
    """Reports if the app is running in the first generation sandbox.

    The second generation runtimes are technically still in a sandbox, but it
    is much less restrictive, so generally you shouldn't need to check for it.
    see https://cloud.google.com/appengine/docs/standard/runtimes
    """
    ...

def is_local_appengine(): # -> bool:
    ...

def is_prod_appengine(): # -> bool:
    ...

def is_prod_appengine_mvms(): # -> Literal[False]:
    """Deprecated."""
    ...

